[package]
name = "transaction-handler-microservice"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.9"
tokio = {version = "1", features = ["full"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
